log-K8S now configures svcat completion
log-K8S now configures svcat completion which depends on kube config

Otherwise fails when following command is run as root without kubeconfig:

```
$ /usr/local/bin/svcat completion bash > /etc/bash_completion.d/svcat 
Error: could not get Kubernetes config for context "": invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```