Fix ruby and ytt installation. Introduce a minimal image cli checks
For `svcat` command to avoid error below, we use help option instead of version:

```
svcat version --client
Error: could not get Kubernetes config for context "": invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```